In [3]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

In [4]:
normal = tfd.Normal(loc=0, scale = 1.)

In [5]:
print(normal)

tfp.distributions.Normal("Normal", batch_shape=[], event_shape=[], dtype=float32)


In [6]:
normal.sample()

<tf.Tensor: shape=(), dtype=float32, numpy=0.99155706>

In [7]:
normal.sample(3)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 2.1106098,  1.0984638, -0.393667 ], dtype=float32)>

In [9]:
normal.prob(0.5)

<tf.Tensor: shape=(), dtype=float32, numpy=0.35206532>

In [10]:
normal.log_prob(0.5)

<tf.Tensor: shape=(), dtype=float32, numpy=-1.0439385>

In [11]:
bernoulli = tfd.Bernoulli(probs=0.7)
print(bernoulli)

tfp.distributions.Bernoulli("Bernoulli", batch_shape=[], event_shape=[], dtype=int32)


In [12]:
bernoulli = tfd.Bernoulli(probs=0.7)
print(bernoulli)

tfp.distributions.Bernoulli("Bernoulli", batch_shape=[], event_shape=[], dtype=int32)


In [13]:
bernoulli = tfd.Bernoulli(probs=0.7)
bernoulli.sample(3)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 1, 1], dtype=int32)>

In [15]:
bernoulli = tfd.Bernoulli(probs=[0.4, 0.5])
print(bernoulli)

tfp.distributions.Bernoulli("Bernoulli", batch_shape=[2], event_shape=[], dtype=int32)


In [17]:
bernoulli.batch_shape

TensorShape([2])