In [1]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

In [2]:
mv_normal = tfd.MultivariateNormalDiag(loc=[-1., 0.5], scale_diag=[1., 1.5])
print(mv_normal)

tfp.distributions.MultivariateNormalDiag("MultivariateNormalDiag", batch_shape=[], event_shape=[2], dtype=float32)


In [3]:
mv_normal = tfd.MultivariateNormalDiag(loc=[-1., 0.5], scale_diag=[1., 1.5])
mv_normal.sample(3)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.03560925, -0.9064474 ],
       [-0.3578266 , -0.7053442 ],
       [-0.38168263, -0.46170372]], dtype=float32)>

In [5]:
batched_normal = tfd.Normal(loc=[-1., 0.5], scale=[1., 1.5])
batched_normal.sample(3)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-1.6902812 ,  1.2384315 ],
       [-0.57953787, -1.61094   ],
       [-0.0633837 ,  0.8795818 ]], dtype=float32)>

In [7]:
batched_normal = tfd.Normal(loc=[-1., 0.5], scale=[1., 1.5])
batched_normal.log_prob([0.2, 1.8])

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([-1.6389385, -1.699959 ], dtype=float32)>

In [8]:
batched_mv_normal = tfd.MultivariateNormalDiag(
	loc=[[-1., 0.5], [2., 0.], [-0.5, 1.5]],
	scale_diag=[[1., 1.5], [2., 0.5], [1., 1.,]])
batched_mv_normal.sample(2)

<tf.Tensor: shape=(2, 3, 2), dtype=float32, numpy=
array([[[-1.2510694 ,  2.9420712 ],
        [ 4.0344563 , -0.51980674],
        [-1.4906017 ,  1.0412079 ]],

       [[ 0.01786315, -0.14239699],
        [ 0.09706712, -0.48809847],
        [ 2.003863  ,  1.5432464 ]]], dtype=float32)>