In [1]:
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense, Flatten, Conv1D, AveragePooling1D

In [3]:
inputs = Input(shape=(32, 1))
h = Conv1D(16, 5, activation='relu')(inputs)
h = AveragePooling1D(3)(h)
h = Flatten()(h)
outputs = Dense(20, activation='sigmoid')(h)

In [4]:
model = Model(inputs=inputs, outputs=outputs)

In [5]:
print(model.layers)

[<keras.engine.input_layer.InputLayer object at 0x7f0964bcbbe0>, <keras.layers.convolutional.conv1d.Conv1D object at 0x7f0964bcbaf0>, <keras.layers.pooling.average_pooling1d.AveragePooling1D object at 0x7f09cc1c87c0>, <keras.layers.reshaping.flatten.Flatten object at 0x7f0964330250>, <keras.layers.core.dense.Dense object at 0x7f0964bcbfd0>]


In [6]:
print(model.layers[1]) # Conv1D

In [7]:
print(model.layers[1].weights) # Conv1D

[<tf.Variable 'conv1d/kernel:0' shape=(5, 1, 16) dtype=float32, numpy=
array([[[-0.060756  ,  0.13695517, -0.03570372,  0.18512532,
         -0.00160882,  0.13198778,  0.11550191, -0.08320394,
          0.21058288,  0.0067457 ,  0.06377262,  0.05408701,
          0.16305584, -0.10967253,  0.19381082, -0.14174372]],

       [[ 0.18428373,  0.1909472 ,  0.07728109, -0.11191168,
          0.20284393,  0.2216278 , -0.11706074,  0.0703955 ,
         -0.24972086,  0.17653978, -0.19784538,  0.04619756,
         -0.00174341,  0.00679809,  0.0096432 , -0.19114262]],

       [[-0.07557034,  0.09512436, -0.06904647, -0.07475746,
         -0.22935243,  0.17057213, -0.00493628,  0.25592533,
         -0.2149253 ,  0.16291934, -0.163227  ,  0.21095785,
          0.19027755, -0.24964502, -0.09725392,  0.08910668]],

       [[-0.13324459,  0.11611173, -0.0923533 , -0.0174278 ,
          0.00734904,  0.12306792,  0.19574642,  0.09152761,
         -0.09279083, -0.06984189,  0.22875857,  0.13734809,
     

In [8]:
print(model.layers[1].get_weights()) # Conv1D

[array([[[-0.060756  ,  0.13695517, -0.03570372,  0.18512532,
         -0.00160882,  0.13198778,  0.11550191, -0.08320394,
          0.21058288,  0.0067457 ,  0.06377262,  0.05408701,
          0.16305584, -0.10967253,  0.19381082, -0.14174372]],

       [[ 0.18428373,  0.1909472 ,  0.07728109, -0.11191168,
          0.20284393,  0.2216278 , -0.11706074,  0.0703955 ,
         -0.24972086,  0.17653978, -0.19784538,  0.04619756,
         -0.00174341,  0.00679809,  0.0096432 , -0.19114262]],

       [[-0.07557034,  0.09512436, -0.06904647, -0.07475746,
         -0.22935243,  0.17057213, -0.00493628,  0.25592533,
         -0.2149253 ,  0.16291934, -0.163227  ,  0.21095785,
          0.19027755, -0.24964502, -0.09725392,  0.08910668]],

       [[-0.13324459,  0.11611173, -0.0923533 , -0.0174278 ,
          0.00734904,  0.12306792,  0.19574642,  0.09152761,
         -0.09279083, -0.06984189,  0.22875857,  0.13734809,
          0.03439844, -0.21738052,  0.04346317, -0.03684942]],

       [[-0

In [9]:
print(model.layers[1].kernel) # Conv1D

<tf.Variable 'conv1d/kernel:0' shape=(5, 1, 16) dtype=float32, numpy=
array([[[-0.060756  ,  0.13695517, -0.03570372,  0.18512532,
         -0.00160882,  0.13198778,  0.11550191, -0.08320394,
          0.21058288,  0.0067457 ,  0.06377262,  0.05408701,
          0.16305584, -0.10967253,  0.19381082, -0.14174372]],

       [[ 0.18428373,  0.1909472 ,  0.07728109, -0.11191168,
          0.20284393,  0.2216278 , -0.11706074,  0.0703955 ,
         -0.24972086,  0.17653978, -0.19784538,  0.04619756,
         -0.00174341,  0.00679809,  0.0096432 , -0.19114262]],

       [[-0.07557034,  0.09512436, -0.06904647, -0.07475746,
         -0.22935243,  0.17057213, -0.00493628,  0.25592533,
         -0.2149253 ,  0.16291934, -0.163227  ,  0.21095785,
          0.19027755, -0.24964502, -0.09725392,  0.08910668]],

       [[-0.13324459,  0.11611173, -0.0923533 , -0.0174278 ,
          0.00734904,  0.12306792,  0.19574642,  0.09152761,
         -0.09279083, -0.06984189,  0.22875857,  0.13734809,
      

In [10]:
print(model.layers[1].bias) # Conv1D

<tf.Variable 'conv1d/bias:0' shape=(16,) dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
      dtype=float32)>


In [15]:
inputs = Input(shape=(32, 1), name= 'input_layer')
h = Conv1D(16, 5, activation='relu', name = 'conv1d_layer')(inputs)
h = AveragePooling1D(3, name = 'avg_pool1d_layer')(h)
h = Flatten(name = 'flatten_layer')(h)
outputs = Dense(20, activation='sigmoid', name = 'dense_layer')(h)

In [16]:
model = Model(inputs=inputs, outputs=outputs)

In [18]:
print(model.get_layer('conv1d_layer').bias) # Conv1D

<tf.Variable 'conv1d_layer/bias:0' shape=(16,) dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
      dtype=float32)>


In [19]:
print(model.get_layer('conv1d_layer').input) # input
print(model.get_layer('conv1d_layer').input) # output

KerasTensor(type_spec=TensorSpec(shape=(None, 32, 1), dtype=tf.float32, name='input_layer'), name='input_layer', description="created by layer 'input_layer'")
KerasTensor(type_spec=TensorSpec(shape=(None, 32, 1), dtype=tf.float32, name='input_layer'), name='input_layer', description="created by layer 'input_layer'")


In [20]:
flatten_output = model.get_layer('flatten_layer').output

In [21]:
model2 = Model(inputs = model.input, outputs = flatten_output)

In [23]:
from tensorflow.keras.models import Sequential

In [24]:
model3 = Sequential([
    model2,
    Dense(10, activation = 'softmax', name = 'new_dense_layer')

])

In [34]:
new_outputs = Dense(10, activation = 'softmax')(flatten_output)

In [35]:
model3 = Model(inputs = model2.input, outputs = new_outputs)